// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230207.1

#pragma once
#ifndef WINRT_Microsoft_Terminal_Core_H
#define WINRT_Microsoft_Terminal_Core_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.230207.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.230207.1"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Microsoft.Terminal.Core.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::DefaultForeground() const
    {
        winrt::Microsoft::Terminal::Core::Color value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->get_DefaultForeground(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::DefaultForeground(winrt::Microsoft::Terminal::Core::Color const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->put_DefaultForeground(impl::bind_in(value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::DefaultBackground() const
    {
        winrt::Microsoft::Terminal::Core::Color value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->get_DefaultBackground(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::DefaultBackground(winrt::Microsoft::Terminal::Core::Color const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->put_DefaultBackground(impl::bind_in(value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::SelectionBackground() const
    {
        winrt::Microsoft::Terminal::Core::Color value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->get_SelectionBackground(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::SelectionBackground(winrt::Microsoft::Terminal::Core::Color const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->put_SelectionBackground(impl::bind_in(value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::GetColorTableEntry(int32_t index) const
    {
        winrt::Microsoft::Terminal::Core::Color result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->GetColorTableEntry(index, put_abi(result)));
        return result;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::CursorColor() const
    {
        winrt::Microsoft::Terminal::Core::Color value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->get_CursorColor(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::CursorColor(winrt::Microsoft::Terminal::Core::Color const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->put_CursorColor(impl::bind_in(value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::CursorShape() const
    {
        winrt::Microsoft::Terminal::Core::CursorStyle value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->get_CursorShape(reinterpret_cast<int32_t*>(&value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::CursorShape(winrt::Microsoft::Terminal::Core::CursorStyle const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->put_CursorShape(static_cast<int32_t>(value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::CursorHeight() const
    {
        uint32_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->get_CursorHeight(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::CursorHeight(uint32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->put_CursorHeight(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::IntenseIsBold() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->get_IntenseIsBold(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::IntenseIsBold(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->put_IntenseIsBold(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::IntenseIsBright() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->get_IntenseIsBright(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::IntenseIsBright(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->put_IntenseIsBright(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::AdjustIndistinguishableColors() const
    {
        winrt::Microsoft::Terminal::Core::AdjustTextMode value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->get_AdjustIndistinguishableColors(reinterpret_cast<int32_t*>(&value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreAppearance<D>::AdjustIndistinguishableColors(winrt::Microsoft::Terminal::Core::AdjustTextMode const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreAppearance)->put_AdjustIndistinguishableColors(static_cast<int32_t>(value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::HistorySize() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_HistorySize(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::HistorySize(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_HistorySize(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::InitialRows() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_InitialRows(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::InitialRows(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_InitialRows(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::InitialCols() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_InitialCols(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::InitialCols(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_InitialCols(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::SnapOnInput() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_SnapOnInput(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::SnapOnInput(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_SnapOnInput(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::AltGrAliasing() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_AltGrAliasing(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::AltGrAliasing(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_AltGrAliasing(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::AnswerbackMessage() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_AnswerbackMessage(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::AnswerbackMessage(param::hstring const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_AnswerbackMessage(*(void**)(&value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::StartingTitle() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_StartingTitle(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::StartingTitle(param::hstring const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_StartingTitle(*(void**)(&value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::SuppressApplicationTitle() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_SuppressApplicationTitle(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::SuppressApplicationTitle(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_SuppressApplicationTitle(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::WordDelimiters() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_WordDelimiters(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::WordDelimiters(param::hstring const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_WordDelimiters(*(void**)(&value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::ForceVTInput() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_ForceVTInput(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::ForceVTInput(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_ForceVTInput(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::TrimBlockSelection() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_TrimBlockSelection(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::TrimBlockSelection(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_TrimBlockSelection(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::DetectURLs() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_DetectURLs(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::DetectURLs(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_DetectURLs(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::TabColor() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_TabColor(&value));
        return winrt::Windows::Foundation::IReference<winrt::Microsoft::Terminal::Core::Color>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::TabColor(winrt::Windows::Foundation::IReference<winrt::Microsoft::Terminal::Core::Color> const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_TabColor(*(void**)(&value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::StartingTabColor() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_StartingTabColor(&value));
        return winrt::Windows::Foundation::IReference<winrt::Microsoft::Terminal::Core::Color>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::StartingTabColor(winrt::Windows::Foundation::IReference<winrt::Microsoft::Terminal::Core::Color> const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_StartingTabColor(*(void**)(&value)));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::AutoMarkPrompts() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_AutoMarkPrompts(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::AutoMarkPrompts(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_AutoMarkPrompts(value));
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::RainbowSuggestions() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->get_RainbowSuggestions(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Terminal_Core_ICoreSettings<D>::RainbowSuggestions(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Terminal::Core::ICoreSettings)->put_RainbowSuggestions(value));
    }
    template <typename D>
    struct produce<D, winrt::Microsoft::Terminal::Core::ICoreAppearance> : produce_base<D, winrt::Microsoft::Terminal::Core::ICoreAppearance>
    {
        int32_t __stdcall get_DefaultForeground(struct struct_Microsoft_Terminal_Core_Color* value) noexcept final try
        {
            zero_abi<winrt::Microsoft::Terminal::Core::Color>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Terminal::Core::Color>(this->shim().DefaultForeground());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_DefaultForeground(struct struct_Microsoft_Terminal_Core_Color value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().DefaultForeground(*reinterpret_cast<winrt::Microsoft::Terminal::Core::Color const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_DefaultBackground(struct struct_Microsoft_Terminal_Core_Color* value) noexcept final try
        {
            zero_abi<winrt::Microsoft::Terminal::Core::Color>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Terminal::Core::Color>(this->shim().DefaultBackground());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_DefaultBackground(struct struct_Microsoft_Terminal_Core_Color value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().DefaultBackground(*reinterpret_cast<winrt::Microsoft::Terminal::Core::Color const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_SelectionBackground(struct struct_Microsoft_Terminal_Core_Color* value) noexcept final try
        {
            zero_abi<winrt::Microsoft::Terminal::Core::Color>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Terminal::Core::Color>(this->shim().SelectionBackground());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_SelectionBackground(struct struct_Microsoft_Terminal_Core_Color value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SelectionBackground(*reinterpret_cast<winrt::Microsoft::Terminal::Core::Color const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetColorTableEntry(int32_t index, struct struct_Microsoft_Terminal_Core_Color* result) noexcept final try
        {
            zero_abi<winrt::Microsoft::Terminal::Core::Color>(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Terminal::Core::Color>(this->shim().GetColorTableEntry(index));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_CursorColor(struct struct_Microsoft_Terminal_Core_Color* value) noexcept final try
        {
            zero_abi<winrt::Microsoft::Terminal::Core::Color>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Terminal::Core::Color>(this->shim().CursorColor());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_CursorColor(struct struct_Microsoft_Terminal_Core_Color value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().CursorColor(*reinterpret_cast<winrt::Microsoft::Terminal::Core::Color const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_CursorShape(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Terminal::Core::CursorStyle>(this->shim().CursorShape());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_CursorShape(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().CursorShape(*reinterpret_cast<winrt::Microsoft::Terminal::Core::CursorStyle const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_CursorHeight(uint32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<uint32_t>(this->shim().CursorHeight());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_CursorHeight(uint32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().CursorHeight(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_IntenseIsBold(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IntenseIsBold());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_IntenseIsBold(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IntenseIsBold(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_IntenseIsBright(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IntenseIsBright());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_IntenseIsBright(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IntenseIsBright(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_AdjustIndistinguishableColors(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Terminal::Core::AdjustTextMode>(this->shim().AdjustIndistinguishableColors());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_AdjustIndistinguishableColors(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().AdjustIndistinguishableColors(*reinterpret_cast<winrt::Microsoft::Terminal::Core::AdjustTextMode const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::Microsoft::Terminal::Core::ICoreSettings> : produce_base<D, winrt::Microsoft::Terminal::Core::ICoreSettings>
    {
        int32_t __stdcall get_HistorySize(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().HistorySize());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_HistorySize(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().HistorySize(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_InitialRows(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().InitialRows());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_InitialRows(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().InitialRows(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_InitialCols(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().InitialCols());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_InitialCols(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().InitialCols(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_SnapOnInput(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().SnapOnInput());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_SnapOnInput(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SnapOnInput(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_AltGrAliasing(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().AltGrAliasing());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_AltGrAliasing(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().AltGrAliasing(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_AnswerbackMessage(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().AnswerbackMessage());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_AnswerbackMessage(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().AnswerbackMessage(*reinterpret_cast<hstring const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_StartingTitle(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().StartingTitle());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_StartingTitle(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().StartingTitle(*reinterpret_cast<hstring const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_SuppressApplicationTitle(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().SuppressApplicationTitle());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_SuppressApplicationTitle(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SuppressApplicationTitle(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_WordDelimiters(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().WordDelimiters());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_WordDelimiters(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().WordDelimiters(*reinterpret_cast<hstring const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_ForceVTInput(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().ForceVTInput());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_ForceVTInput(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().ForceVTInput(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_TrimBlockSelection(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().TrimBlockSelection());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_TrimBlockSelection(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().TrimBlockSelection(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_DetectURLs(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().DetectURLs());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_DetectURLs(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().DetectURLs(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_TabColor(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::IReference<winrt::Microsoft::Terminal::Core::Color>>(this->shim().TabColor());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_TabColor(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().TabColor(*reinterpret_cast<winrt::Windows::Foundation::IReference<winrt::Microsoft::Terminal::Core::Color> const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_StartingTabColor(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::IReference<winrt::Microsoft::Terminal::Core::Color>>(this->shim().StartingTabColor());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_StartingTabColor(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().StartingTabColor(*reinterpret_cast<winrt::Windows::Foundation::IReference<winrt::Microsoft::Terminal::Core::Color> const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_AutoMarkPrompts(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().AutoMarkPrompts());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_AutoMarkPrompts(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().AutoMarkPrompts(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_RainbowSuggestions(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().RainbowSuggestions());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_RainbowSuggestions(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().RainbowSuggestions(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::Microsoft::Terminal::Core
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Microsoft::Terminal::Core::ICoreAppearance> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Terminal::Core::ICoreSettings> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
