// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230207.1

#pragma once
#ifndef WINRT_Microsoft_Terminal_Core_1_H
#define WINRT_Microsoft_Terminal_Core_1_H
#include "winrt/impl/Microsoft.Terminal.Core.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Terminal::Core
{
    struct WINRT_IMPL_EMPTY_BASES ICoreAppearance :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICoreAppearance>
    {
        ICoreAppearance(std::nullptr_t = nullptr) noexcept {}
        ICoreAppearance(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICoreSettings :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICoreSettings>,
        impl::require<winrt::Microsoft::Terminal::Core::ICoreSettings, winrt::Microsoft::Terminal::Core::ICoreAppearance>
    {
        ICoreSettings(std::nullptr_t = nullptr) noexcept {}
        ICoreSettings(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
