// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230207.1

#pragma once
#ifndef WINRT_Microsoft_Terminal_Core_0_H
#define WINRT_Microsoft_Terminal_Core_0_H
WINRT_EXPORT namespace winrt::Windows::Foundation
{
    template <typename T> struct WINRT_IMPL_EMPTY_BASES IReference;
}
WINRT_EXPORT namespace winrt::Microsoft::Terminal::Core
{
    enum class AdjustTextMode : int32_t
    {
        Never = 0,
        Indexed = 1,
        Always = 2,
    };
    enum class CursorStyle : int32_t
    {
        Vintage = 0,
        Bar = 1,
        Underscore = 2,
        DoubleUnderscore = 3,
        FilledBox = 4,
        EmptyBox = 5,
    };
    enum class MatchMode : int32_t
    {
        None = 0,
        All = 1,
    };
    struct ICoreAppearance;
    struct ICoreSettings;
    struct Color;
    struct ControlKeyStates;
    struct OptionalColor;
    struct Padding;
    struct Point;
    struct Scheme;
}
namespace winrt::impl
{
    template <> struct category<winrt::Microsoft::Terminal::Core::ICoreAppearance>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Terminal::Core::ICoreSettings>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Terminal::Core::AdjustTextMode>{ using type = enum_category; };
    template <> struct category<winrt::Microsoft::Terminal::Core::CursorStyle>{ using type = enum_category; };
    template <> struct category<winrt::Microsoft::Terminal::Core::MatchMode>{ using type = enum_category; };
    template <> struct category<winrt::Microsoft::Terminal::Core::Color>{ using type = struct_category<uint8_t, uint8_t, uint8_t, uint8_t>; };
    template <> struct category<winrt::Microsoft::Terminal::Core::ControlKeyStates>{ using type = struct_category<uint32_t>; };
    template <> struct category<winrt::Microsoft::Terminal::Core::OptionalColor>{ using type = struct_category<bool, winrt::Microsoft::Terminal::Core::Color>; };
    template <> struct category<winrt::Microsoft::Terminal::Core::Padding>{ using type = struct_category<float, float, float, float>; };
    template <> struct category<winrt::Microsoft::Terminal::Core::Point>{ using type = struct_category<int32_t, int32_t>; };
    template <> struct category<winrt::Microsoft::Terminal::Core::Scheme>{ using type = struct_category<winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color, winrt::Microsoft::Terminal::Core::Color>; };
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::AdjustTextMode> = L"Microsoft.Terminal.Core.AdjustTextMode";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::CursorStyle> = L"Microsoft.Terminal.Core.CursorStyle";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::MatchMode> = L"Microsoft.Terminal.Core.MatchMode";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::Color> = L"Microsoft.Terminal.Core.Color";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::ControlKeyStates> = L"Microsoft.Terminal.Core.ControlKeyStates";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::OptionalColor> = L"Microsoft.Terminal.Core.OptionalColor";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::Padding> = L"Microsoft.Terminal.Core.Padding";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::Point> = L"Microsoft.Terminal.Core.Point";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::Scheme> = L"Microsoft.Terminal.Core.Scheme";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::ICoreAppearance> = L"Microsoft.Terminal.Core.ICoreAppearance";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Terminal::Core::ICoreSettings> = L"Microsoft.Terminal.Core.ICoreSettings";
    template <> inline constexpr guid guid_v<winrt::Microsoft::Terminal::Core::ICoreAppearance>{ 0x7C09AD18,0xC06C,0x5A35,{ 0xA8,0xE6,0x3F,0x6C,0x87,0x23,0x5A,0x40 } }; // 7C09AD18-C06C-5A35-A8E6-3F6C87235A40
    template <> inline constexpr guid guid_v<winrt::Microsoft::Terminal::Core::ICoreSettings>{ 0x7F682A8D,0x0883,0x5338,{ 0xB0,0x56,0x29,0xF9,0x22,0xB8,0x53,0x6C } }; // 7F682A8D-0883-5338-B056-29F922B8536C
    template <> struct abi<winrt::Microsoft::Terminal::Core::ICoreAppearance>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_DefaultForeground(struct struct_Microsoft_Terminal_Core_Color*) noexcept = 0;
            virtual int32_t __stdcall put_DefaultForeground(struct struct_Microsoft_Terminal_Core_Color) noexcept = 0;
            virtual int32_t __stdcall get_DefaultBackground(struct struct_Microsoft_Terminal_Core_Color*) noexcept = 0;
            virtual int32_t __stdcall put_DefaultBackground(struct struct_Microsoft_Terminal_Core_Color) noexcept = 0;
            virtual int32_t __stdcall get_SelectionBackground(struct struct_Microsoft_Terminal_Core_Color*) noexcept = 0;
            virtual int32_t __stdcall put_SelectionBackground(struct struct_Microsoft_Terminal_Core_Color) noexcept = 0;
            virtual int32_t __stdcall GetColorTableEntry(int32_t, struct struct_Microsoft_Terminal_Core_Color*) noexcept = 0;
            virtual int32_t __stdcall get_CursorColor(struct struct_Microsoft_Terminal_Core_Color*) noexcept = 0;
            virtual int32_t __stdcall put_CursorColor(struct struct_Microsoft_Terminal_Core_Color) noexcept = 0;
            virtual int32_t __stdcall get_CursorShape(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_CursorShape(int32_t) noexcept = 0;
            virtual int32_t __stdcall get_CursorHeight(uint32_t*) noexcept = 0;
            virtual int32_t __stdcall put_CursorHeight(uint32_t) noexcept = 0;
            virtual int32_t __stdcall get_IntenseIsBold(bool*) noexcept = 0;
            virtual int32_t __stdcall put_IntenseIsBold(bool) noexcept = 0;
            virtual int32_t __stdcall get_IntenseIsBright(bool*) noexcept = 0;
            virtual int32_t __stdcall put_IntenseIsBright(bool) noexcept = 0;
            virtual int32_t __stdcall get_AdjustIndistinguishableColors(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_AdjustIndistinguishableColors(int32_t) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Terminal::Core::ICoreSettings>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_HistorySize(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_HistorySize(int32_t) noexcept = 0;
            virtual int32_t __stdcall get_InitialRows(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_InitialRows(int32_t) noexcept = 0;
            virtual int32_t __stdcall get_InitialCols(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_InitialCols(int32_t) noexcept = 0;
            virtual int32_t __stdcall get_SnapOnInput(bool*) noexcept = 0;
            virtual int32_t __stdcall put_SnapOnInput(bool) noexcept = 0;
            virtual int32_t __stdcall get_AltGrAliasing(bool*) noexcept = 0;
            virtual int32_t __stdcall put_AltGrAliasing(bool) noexcept = 0;
            virtual int32_t __stdcall get_AnswerbackMessage(void**) noexcept = 0;
            virtual int32_t __stdcall put_AnswerbackMessage(void*) noexcept = 0;
            virtual int32_t __stdcall get_StartingTitle(void**) noexcept = 0;
            virtual int32_t __stdcall put_StartingTitle(void*) noexcept = 0;
            virtual int32_t __stdcall get_SuppressApplicationTitle(bool*) noexcept = 0;
            virtual int32_t __stdcall put_SuppressApplicationTitle(bool) noexcept = 0;
            virtual int32_t __stdcall get_WordDelimiters(void**) noexcept = 0;
            virtual int32_t __stdcall put_WordDelimiters(void*) noexcept = 0;
            virtual int32_t __stdcall get_ForceVTInput(bool*) noexcept = 0;
            virtual int32_t __stdcall put_ForceVTInput(bool) noexcept = 0;
            virtual int32_t __stdcall get_TrimBlockSelection(bool*) noexcept = 0;
            virtual int32_t __stdcall put_TrimBlockSelection(bool) noexcept = 0;
            virtual int32_t __stdcall get_DetectURLs(bool*) noexcept = 0;
            virtual int32_t __stdcall put_DetectURLs(bool) noexcept = 0;
            virtual int32_t __stdcall get_TabColor(void**) noexcept = 0;
            virtual int32_t __stdcall put_TabColor(void*) noexcept = 0;
            virtual int32_t __stdcall get_StartingTabColor(void**) noexcept = 0;
            virtual int32_t __stdcall put_StartingTabColor(void*) noexcept = 0;
            virtual int32_t __stdcall get_AutoMarkPrompts(bool*) noexcept = 0;
            virtual int32_t __stdcall put_AutoMarkPrompts(bool) noexcept = 0;
            virtual int32_t __stdcall get_RainbowSuggestions(bool*) noexcept = 0;
            virtual int32_t __stdcall put_RainbowSuggestions(bool) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Microsoft_Terminal_Core_ICoreAppearance
    {
        [[nodiscard]] auto DefaultForeground() const;
        auto DefaultForeground(winrt::Microsoft::Terminal::Core::Color const& value) const;
        [[nodiscard]] auto DefaultBackground() const;
        auto DefaultBackground(winrt::Microsoft::Terminal::Core::Color const& value) const;
        [[nodiscard]] auto SelectionBackground() const;
        auto SelectionBackground(winrt::Microsoft::Terminal::Core::Color const& value) const;
        auto GetColorTableEntry(int32_t index) const;
        [[nodiscard]] auto CursorColor() const;
        auto CursorColor(winrt::Microsoft::Terminal::Core::Color const& value) const;
        [[nodiscard]] auto CursorShape() const;
        auto CursorShape(winrt::Microsoft::Terminal::Core::CursorStyle const& value) const;
        [[nodiscard]] auto CursorHeight() const;
        auto CursorHeight(uint32_t value) const;
        [[nodiscard]] auto IntenseIsBold() const;
        auto IntenseIsBold(bool value) const;
        [[nodiscard]] auto IntenseIsBright() const;
        auto IntenseIsBright(bool value) const;
        [[nodiscard]] auto AdjustIndistinguishableColors() const;
        auto AdjustIndistinguishableColors(winrt::Microsoft::Terminal::Core::AdjustTextMode const& value) const;
    };
    template <> struct consume<winrt::Microsoft::Terminal::Core::ICoreAppearance>
    {
        template <typename D> using type = consume_Microsoft_Terminal_Core_ICoreAppearance<D>;
    };
    template <typename D>
    struct consume_Microsoft_Terminal_Core_ICoreSettings
    {
        [[nodiscard]] auto HistorySize() const;
        auto HistorySize(int32_t value) const;
        [[nodiscard]] auto InitialRows() const;
        auto InitialRows(int32_t value) const;
        [[nodiscard]] auto InitialCols() const;
        auto InitialCols(int32_t value) const;
        [[nodiscard]] auto SnapOnInput() const;
        auto SnapOnInput(bool value) const;
        [[nodiscard]] auto AltGrAliasing() const;
        auto AltGrAliasing(bool value) const;
        [[nodiscard]] auto AnswerbackMessage() const;
        auto AnswerbackMessage(param::hstring const& value) const;
        [[nodiscard]] auto StartingTitle() const;
        auto StartingTitle(param::hstring const& value) const;
        [[nodiscard]] auto SuppressApplicationTitle() const;
        auto SuppressApplicationTitle(bool value) const;
        [[nodiscard]] auto WordDelimiters() const;
        auto WordDelimiters(param::hstring const& value) const;
        [[nodiscard]] auto ForceVTInput() const;
        auto ForceVTInput(bool value) const;
        [[nodiscard]] auto TrimBlockSelection() const;
        auto TrimBlockSelection(bool value) const;
        [[nodiscard]] auto DetectURLs() const;
        auto DetectURLs(bool value) const;
        [[nodiscard]] auto TabColor() const;
        auto TabColor(winrt::Windows::Foundation::IReference<winrt::Microsoft::Terminal::Core::Color> const& value) const;
        [[nodiscard]] auto StartingTabColor() const;
        auto StartingTabColor(winrt::Windows::Foundation::IReference<winrt::Microsoft::Terminal::Core::Color> const& value) const;
        [[nodiscard]] auto AutoMarkPrompts() const;
        auto AutoMarkPrompts(bool value) const;
        [[nodiscard]] auto RainbowSuggestions() const;
        auto RainbowSuggestions(bool value) const;
    };
    template <> struct consume<winrt::Microsoft::Terminal::Core::ICoreSettings>
    {
        template <typename D> using type = consume_Microsoft_Terminal_Core_ICoreSettings<D>;
    };
    struct struct_Microsoft_Terminal_Core_Color
    {
        uint8_t R;
        uint8_t G;
        uint8_t B;
        uint8_t A;
    };
    template <> struct abi<Microsoft::Terminal::Core::Color>
    {
        using type = struct_Microsoft_Terminal_Core_Color;
    };
    struct struct_Microsoft_Terminal_Core_ControlKeyStates
    {
        uint32_t Value;
    };
    template <> struct abi<Microsoft::Terminal::Core::ControlKeyStates>
    {
        using type = struct_Microsoft_Terminal_Core_ControlKeyStates;
    };
    struct struct_Microsoft_Terminal_Core_OptionalColor
    {
        bool HasValue;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } Color;
    };
    template <> struct abi<Microsoft::Terminal::Core::OptionalColor>
    {
        using type = struct_Microsoft_Terminal_Core_OptionalColor;
    };
    struct struct_Microsoft_Terminal_Core_Padding
    {
        float Left;
        float Top;
        float Right;
        float Bottom;
    };
    template <> struct abi<Microsoft::Terminal::Core::Padding>
    {
        using type = struct_Microsoft_Terminal_Core_Padding;
    };
    struct struct_Microsoft_Terminal_Core_Point
    {
        int32_t X;
        int32_t Y;
    };
    template <> struct abi<Microsoft::Terminal::Core::Point>
    {
        using type = struct_Microsoft_Terminal_Core_Point;
    };
    struct struct_Microsoft_Terminal_Core_Scheme
    {
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } Foreground;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } Background;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } SelectionBackground;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } CursorColor;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } Black;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } Red;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } Green;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } Yellow;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } Blue;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } Purple;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } Cyan;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } White;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } BrightBlack;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } BrightRed;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } BrightGreen;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } BrightYellow;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } BrightBlue;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } BrightPurple;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } BrightCyan;
        struct{ uint8_t R; uint8_t G; uint8_t B; uint8_t A; } BrightWhite;
    };
    template <> struct abi<Microsoft::Terminal::Core::Scheme>
    {
        using type = struct_Microsoft_Terminal_Core_Scheme;
    };
}
#endif
