// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230207.1

#pragma once
#ifndef WINRT_Microsoft_Terminal_Core_2_H
#define WINRT_Microsoft_Terminal_Core_2_H
#include "winrt/impl/Microsoft.Terminal.Core.1.h"
WINRT_EXPORT namespace winrt::Microsoft::Terminal::Core
{
    struct Color
    {
        uint8_t R;
        uint8_t G;
        uint8_t B;
        uint8_t A;
    };
    inline bool operator==(Color const& left, Color const& right) noexcept
    {
        return left.R == right.R && left.G == right.G && left.B == right.B && left.A == right.A;
    }
    inline bool operator!=(Color const& left, Color const& right) noexcept
    {
        return !(left == right);
    }
    struct ControlKeyStates
    {
        uint32_t Value;
    };
    inline bool operator==(ControlKeyStates const& left, ControlKeyStates const& right) noexcept
    {
        return left.Value == right.Value;
    }
    inline bool operator!=(ControlKeyStates const& left, ControlKeyStates const& right) noexcept
    {
        return !(left == right);
    }
    struct OptionalColor
    {
        bool HasValue;
        winrt::Microsoft::Terminal::Core::Color Color;
    };
    inline bool operator==(OptionalColor const& left, OptionalColor const& right) noexcept
    {
        return left.HasValue == right.HasValue && left.Color == right.Color;
    }
    inline bool operator!=(OptionalColor const& left, OptionalColor const& right) noexcept
    {
        return !(left == right);
    }
    struct Padding
    {
        float Left;
        float Top;
        float Right;
        float Bottom;
    };
    inline bool operator==(Padding const& left, Padding const& right) noexcept
    {
        return left.Left == right.Left && left.Top == right.Top && left.Right == right.Right && left.Bottom == right.Bottom;
    }
    inline bool operator!=(Padding const& left, Padding const& right) noexcept
    {
        return !(left == right);
    }
    struct Point
    {
        int32_t X;
        int32_t Y;
    };
    inline bool operator==(Point const& left, Point const& right) noexcept
    {
        return left.X == right.X && left.Y == right.Y;
    }
    inline bool operator!=(Point const& left, Point const& right) noexcept
    {
        return !(left == right);
    }
    struct Scheme
    {
        winrt::Microsoft::Terminal::Core::Color Foreground;
        winrt::Microsoft::Terminal::Core::Color Background;
        winrt::Microsoft::Terminal::Core::Color SelectionBackground;
        winrt::Microsoft::Terminal::Core::Color CursorColor;
        winrt::Microsoft::Terminal::Core::Color Black;
        winrt::Microsoft::Terminal::Core::Color Red;
        winrt::Microsoft::Terminal::Core::Color Green;
        winrt::Microsoft::Terminal::Core::Color Yellow;
        winrt::Microsoft::Terminal::Core::Color Blue;
        winrt::Microsoft::Terminal::Core::Color Purple;
        winrt::Microsoft::Terminal::Core::Color Cyan;
        winrt::Microsoft::Terminal::Core::Color White;
        winrt::Microsoft::Terminal::Core::Color BrightBlack;
        winrt::Microsoft::Terminal::Core::Color BrightRed;
        winrt::Microsoft::Terminal::Core::Color BrightGreen;
        winrt::Microsoft::Terminal::Core::Color BrightYellow;
        winrt::Microsoft::Terminal::Core::Color BrightBlue;
        winrt::Microsoft::Terminal::Core::Color BrightPurple;
        winrt::Microsoft::Terminal::Core::Color BrightCyan;
        winrt::Microsoft::Terminal::Core::Color BrightWhite;
    };
    inline bool operator==(Scheme const& left, Scheme const& right) noexcept
    {
        return left.Foreground == right.Foreground && left.Background == right.Background && left.SelectionBackground == right.SelectionBackground && left.CursorColor == right.CursorColor && left.Black == right.Black && left.Red == right.Red && left.Green == right.Green && left.Yellow == right.Yellow && left.Blue == right.Blue && left.Purple == right.Purple && left.Cyan == right.Cyan && left.White == right.White && left.BrightBlack == right.BrightBlack && left.BrightRed == right.BrightRed && left.BrightGreen == right.BrightGreen && left.BrightYellow == right.BrightYellow && left.BrightBlue == right.BrightBlue && left.BrightPurple == right.BrightPurple && left.BrightCyan == right.BrightCyan && left.BrightWhite == right.BrightWhite;
    }
    inline bool operator!=(Scheme const& left, Scheme const& right) noexcept
    {
        return !(left == right);
    }
}
#endif
